language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]]; then echo "hhvm.enable_zend_compat = true" >> /etc/hhvm/php.ini; else printf "\n" | pecl install yaml; fi

install:
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
