language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - sudo apt-get install -y libyaml-dev
  - sudo pecl install yaml-beta && echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
