language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - if [[ $TRAVIS_PHP_VERSION == "7.0" ]]; then printf "\n" | pecl install yaml; fi
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then printf "\n" | pecl install yaml-beta; fi

install:
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
